version: '3.8'

services:
  frontend:
    image: demoweb-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    deploy:
      replicas: 1  # Cambiar de 3 a 1 para debug
      restart_policy:
        condition: on-failure

  backend:
    image: demoweb-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - POSTGRES_HOST=database  # ✅ Cambiar de 'cafe-aroma_database' a 'database'
      - POSTGRES_DB=cafeAroma
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    networks:
      - app-network
    depends_on:
      - database  # ✅ Cambiar de 'postgres' a 'database'
    deploy:
      replicas: 1  # Cambiar de 2 a 1 para debug
      restart_policy:
        condition: on-failure

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: cafeAroma
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local