version: '3.8'

services:
  frontend:
    image: demoweb-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  backend:
    image: demoweb-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=cafeAroma
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    networks:
      - app-network
    depends_on:
      - postgres
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  # mongodb:
  #   image: mongo:4.4-focal
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - app-network
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #     placement:
  #       constraints:
  #         - node.role == manager

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: cafeAroma
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  mongo-data:
    driver: local
  postgres_data: